--Felipe Augusto Arruda 1948423
--João Marcelo Tozato 1913310
--Vinicius Ribeiro Furlan 1913409

-- TESTANDO KMEANS_FN COM 3 CLUSTERS E 100 ITERACOES
SELECT KMEANS_FN(3, 100);

-- E NECESSARIO EXPORTAR A TABELA CLUSTERS, A FIM DE QUE SEJA POSSIVEL
-- ANALISAR OS RESULTADOS ATRAVES DO CODIGO PYTHON 'PLOT.PY' DISPONIBILIZADO NO ARQUIVO

-- HA DUAS OPCOES PARA ESSE EXPORT
-- FEITO POR ESSE CODIGO
-- INSERIR O PATH ENTRE AS ASPAS SIMPLES
-- SALVAR COMO 'CLUSTERS.CSV' PARA QUE O CODIGO PYTHON FUNCIONE
COPY CLUSTERS TO '~/k-means-plpgsql/clusters.csv' DELIMITER ',' CSV HEADER;
-- OU EXPORTANDO DIRETAMENTE A TABELA A PARTIR DO PGADMIN, QUE POSSIBILITA O EXPORT DAS TABELAS
-- DO DATABASE UTILIZADO, IMPORTANTE RESSALTAR QUE A OPCAO HEADER DEVE SER SELECIONADA


--EXIBICAO DOS RESULTADOS DO KMEANS
SELECT * FROM CLUSTERS;


-- UTILIZANDO ESTA FUNCAO E POSSIVEL USAR NOVAMENTE A FUNCAO KMEANS_FN
-- A FIM DE MUDAR O NUMERO K DE CLUSTERS E O NUMERO DE ITERACOES DESEJADAS
-- ISSO TEM DE SER FEITO APOS O EXPORT DA TABELA CLUSTERS.CSV
SELECT RESET_TABLES();

